fn main() {
    println!("cargo:rerun-if-changed=../c");
    println!("cargo:rerun-if-changed=../more_build/config.h");
    println!("cargo:rustc-link-lib=curses");
    cc::Build::new()
        .files([
            "../c/statics.c",
            "../c/segment.c",
            "../c/alloc.c",
            "../c/symbol.c",
            "../c/intern.c",
            "../c/gcwrapper.c",
            "../c/gc-011.c",
            "../c/gc-par.c",
            "../c/gc-ocd.c",
            "../c/gc-oce.c",
            "../c/number.c",
            "../c/schsig.c",
            "../c/io.c",
            "../c/new-io.c",
            "../c/compress-io.c",
            "../c/fasl.c",
            "../c/vfasl.c",
            "../c/print.c",
            "../c/stats.c",
            "../c/foreign.c",
            "../c/prim.c",
            "../c/prim5.c",
            "../c/flushcache.c",
            "../c/schlib.c",
            "../c/thread.c",
            "../c/expeditor.c",
            "../c/scheme.c",
            "../c/random.c",
            "../c/ffi.c",
            // "../c/self-exe.c",
            // "../c/i3le.c", // "../c/$mo.c",
        ])
        .includes([
            "../lz4/lib",
            "../zlib",
            "../more_build/build/boot/ta6le",
            "../more_build",
        ])
        .flag("-pthread")
        .flag("-m64")
        .flag("-msse2")
        .flag("-Wextra")
        .flag("-Wall")
        .flag("-Wno-unused-parameter")
        .flag("-Wno-unused-function")
        .pic(true)
        .define("X86_64", None)
        .compile("kernel");
}
